services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  
  hr-director:
    build:
      dockerfile: hrDirector.Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:${HR_DIRECTOR_PORT}/
    ports:
      - ${HR_DIRECTOR_PORT}:${HR_DIRECTOR_PORT}
    depends_on:
      - db
  
  hr-manager:
    build:
      dockerfile: hrManager.Dockerfile
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:${HR_MANAGER_PORT}/
    ports:
      - ${HR_MANAGER_PORT}:${HR_MANAGER_PORT}
    depends_on:
      - hr-director

  developer:
    build:
      dockerfile: developer.Dockerfile
    env_file:
      - .env
    depends_on:
      - hr-manager
