services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
