services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - my_private_network
  
  hr-director:
    build:
      dockerfile: hrDirector.Dockerfile
    environment:
        ASPNETCORE_URLS: http://0.0.0.0:${HR_DIRECTOR_PORT}/
        ASPNETCORE_ENVIRONMENT: Development
        DB__CONNECTIONSTRING: Host=db;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
        CSV__DELIMITER: ${CSV_DELIMITER}
        CSV__ENCODING: ${CSV_ENCODING}
        HRDIRECTOR__JUNIORSURL: ${JUNIORS_URL}
        HRDIRECTOR__TEAMLEADSURL: ${TEAM_LEADS_URL}
    ports:
      - ${HR_DIRECTOR_PORT}:${HR_DIRECTOR_PORT}
    depends_on:
      - db
    networks:
      - my_private_network

  hr-manager:
    build:
      dockerfile: hrManager.Dockerfile
    environment:
        ASPNETCORE_URLS: http://0.0.0.0:${HR_MANAGER_PORT}/
        ASPNETCORE_ENVIRONMENT: Development
        CSV__DELIMITER: ${CSV_DELIMITER}
        CSV__ENCODING: ${CSV_ENCODING}
        HRDIRECTOR__CONNECTIONSTRING: http://hr-director:${HR_DIRECTOR_PORT}/
        HRMANAGER__EMPLOYEECOUNT: ${EMPLOYEE_COUNT}
        HRMANAGER__JUNIORSURL: ${JUNIORS_URL}
        HRMANAGER__TEAMLEADSURL: ${TEAM_LEADS_URL}
    ports:
      - ${HR_MANAGER_PORT}:${HR_MANAGER_PORT}
    depends_on:
      - hr-director
    networks:
      - my_private_network

  junior:
    build:
      dockerfile: developer.Dockerfile
    environment:
        CSV__DELIMITER: ${CSV_DELIMITER}
        CSV__ENCODING: ${CSV_ENCODING}
        HRMANAGER__CONNECTIONSTRING: http://hr-manager:${HR_MANAGER_PORT}
        DEVELOPER__ID: 1
        DEVELOPER__TYPE: Junior
        DEVELOPER__JUNIORSURL: ${JUNIORS_URL}
        DEVELOPER__TEAMLEADSURL: ${TEAM_LEADS_URL}
    depends_on:
      - hr-manager
    networks:
      - my_private_network

  team-lead:
    build:
      dockerfile: developer.Dockerfile
    environment:
        CSV__DELIMITER: ${CSV_DELIMITER}
        CSV__ENCODING: ${CSV_ENCODING}
        HRMANAGER__CONNECTIONSTRING: http://hr-manager:${HR_MANAGER_PORT}
        DEVELOPER__ID: 1
        DEVELOPER__TYPE: TeamLead
        DEVELOPER__JUNIORSURL: ${JUNIORS_URL}
        DEVELOPER__TEAMLEADSURL: ${TEAM_LEADS_URL}
    depends_on:
      - hr-manager
    networks:
      - my_private_network

networks:
  my_private_network:
    driver: bridge
