services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  hr-director:
    build:
      dockerfile: hrDirector.Dockerfile
    environment:
        ASPNETCORE_URLS: http://0.0.0.0:${HR_DIRECTOR_PORT}/
        ASPNETCORE_ENVIRONMENT: Development
        Db__ConnectionString: Host=db;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
        HrDirector__JuniorsUrl: ${JUNIORS_URL}
        HrDirector__TeamLeadsUrl: ${TEAM_LEADS_URL}
    ports:
      - ${HR_DIRECTOR_PORT}:${HR_DIRECTOR_PORT}
    depends_on:
      - db

  hr-manager:
    build:
      dockerfile: hrManager.Dockerfile
    environment:
        ASPNETCORE_URLS: http://0.0.0.0:${HR_MANAGER_PORT}/
        ASPNETCORE_ENVIRONMENT: Development
        HrDirector__ConnectionString: http://hr-director:${HR_DIRECTOR_PORT}
        HrManager__EmployeeCount: ${EMPLOYEE_COUNT}
        HrManager__JuniorsUrl: ${JUNIORS_URL}
        HrManager__TeamLeadsUrl: ${TEAM_LEADS_URL}
    ports:
      - ${HR_MANAGER_PORT}:${HR_MANAGER_PORT}
    depends_on:
      - hr-director

  developer:
    build:
      dockerfile: developer.Dockerfile
    environment:
      HrManager__ConnectionString: http://hr-manager:${HR_MANAGER_PORT}
      Developer__JuniorsUrl: ${JUNIORS_URL}
      Developer__TeamLeadsUrl: ${TEAM_LEADS_URL}
    depends_on:
      - hr-manager

  junior-1:
    extends:
      service: developer
    environment:
        Developer__Id: 1
        Developer__Type: Junior

  junior-2:
    extends:
      service: developer
    environment:
      Developer__Id: 2
      Developer__Type: Junior

  junior-3:
    extends:
      service: developer
    environment:
      Developer__Id: 3
      Developer__Type: Junior

  junior-4:
    extends:
      service: developer
    environment:
      Developer__Id: 4
      Developer__Type: Junior

  junior-5:
    extends:
      service: developer
    environment:
      Developer__Id: 5
      Developer__Type: Junior

  team-lead-1:
    extends:
      service: developer
    environment:
      Developer__Id: 1
      Developer__Type: TeamLead

  team-lead-2:
    extends:
      service: developer
    environment:
      Developer__Id: 2
      Developer__Type: TeamLead

  team-lead-3:
    extends:
      service: developer
    environment:
      Developer__Id: 3
      Developer__Type: TeamLead

  team-lead-4:
    extends:
      service: developer
    environment:
      Developer__Id: 4
      Developer__Type: TeamLead

  team-lead-5:
    extends:
      service: developer
    environment:
      Developer__Id: 5
      Developer__Type: TeamLead
