services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  
  hr-director:
    build:
      dockerfile: hrDirector.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5001:5001"
  
  hr-manager:
    build:
      dockerfile: hrManager.Dockerfile
    environment:
      ASPNETCORE_URLS: http://localhost:5001/
    depends_on:
      - hr-director

  developer:
    build:
      dockerfile: developer.Dockerfile
    env_file:
      - .env
    depends_on:
      - hr-manager
