services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 10
  
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 10

  hr-director:
    container_name: hr-director
    build:
      dockerfile: hrDirector.Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:${HR_DIRECTOR_PORT}/
      ASPNETCORE_ENVIRONMENT: Development
      Db__ConnectionString: Host=postgres;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      HrDirector__JuniorsUrl: ${JUNIORS_URL}
      HrDirector__TeamLeadsUrl: ${TEAM_LEADS_URL}
      HrDirector__EmployeeCount: ${EMPLOYEE_COUNT}
      HrDirector__HackathonCount: ${HACKATHON_COUNT}
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: ${RABBITMQ_PORT}
      RabbitMQ__User: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}
    ports:
      - ${HR_DIRECTOR_PORT}:${HR_DIRECTOR_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      junior-1:
        condition: service_started
      junior-2:
        condition: service_started
      junior-3:
        condition: service_started
      junior-4:
        condition: service_started
      junior-5:
        condition: service_started
      team-lead-1:
        condition: service_started
      team-lead-2:
        condition: service_started
      team-lead-3:
        condition: service_started
      team-lead-4:
        condition: service_started
      team-lead-5:
        condition: service_started
        
  hr-manager:
    container_name: hr-manager
    build:
      dockerfile: hrManager.Dockerfile
    environment:
      HrDirector__ConnectionString: http://hr-director:${HR_DIRECTOR_PORT}
      HrManager__EmployeeCount: ${EMPLOYEE_COUNT}
      HrManager__JuniorsUrl: ${JUNIORS_URL}
      HrManager__TeamLeadsUrl: ${TEAM_LEADS_URL}
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: ${RABBITMQ_PORT}
      RabbitMQ__User: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy    
      hr-director:
        condition: service_started
          
  junior-1:
    container_name: junior-1
    build:
      dockerfile: developer.Dockerfile
    environment:
      Developer__JuniorsUrl: ${JUNIORS_URL}
      Developer__TeamLeadsUrl: ${TEAM_LEADS_URL}
      Developer__Id: 1
      Developer__Type: Junior
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: ${RABBITMQ_PORT}
      RabbitMQ__User: ${RABBITMQ_USER}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy

  junior-2:
    container_name: junior-2
    extends:
      service: junior-1
    environment:
      Developer__Id: 2
      Developer__Type: Junior

  junior-3:
    container_name: junior-3
    extends:
      service: junior-1
    environment:
      Developer__Id: 3
      Developer__Type: Junior

  junior-4:
    container_name: junior-4
    extends:
      service: junior-1
    environment:
      Developer__Id: 4
      Developer__Type: Junior

  junior-5:
    container_name: junior-5
    extends:
      service: junior-1
    environment:
      Developer__Id: 5
      Developer__Type: Junior

  team-lead-1:
    container_name: team-lead-1
    extends:
      service: junior-1
    environment:
      Developer__Id: 1
      Developer__Type: TeamLead

  team-lead-2:
    container_name: team-lead-2
    extends:
      service: junior-1
    environment:
      Developer__Id: 2
      Developer__Type: TeamLead

  team-lead-3:
    container_name: team-lead-3
    extends:
      service: junior-1
    environment:
      Developer__Id: 3
      Developer__Type: TeamLead

  team-lead-4:
    container_name: team-lead-4
    extends:
      service: junior-1
    environment:
      Developer__Id: 4
      Developer__Type: TeamLead

  team-lead-5:
    container_name: team-lead-5
    extends:
      service: junior-1
    environment:
      Developer__Id: 5
      Developer__Type: TeamLead
