services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
  
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  hr-director:
    container_name: hr-director
    build:
      dockerfile: hrDirector.Dockerfile
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:${HR_DIRECTOR_PORT}/
      ASPNETCORE_ENVIRONMENT: Development
      Db__ConnectionString: Host=postgres;Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      HrDirector__JuniorsUrl: ${JUNIORS_URL}
      HrDirector__TeamLeadsUrl: ${TEAM_LEADS_URL}
    ports:
      - ${HR_DIRECTOR_PORT}:${HR_DIRECTOR_PORT}
    depends_on:
      - postgres
      - rabbitmq

  hr-manager:
    container_name: hr-manager
    build:
      dockerfile: hrManager.Dockerfile
    environment:
      HrDirector__ConnectionString: http://hr-director:${HR_DIRECTOR_PORT}
      HrManager__EmployeeCount: ${EMPLOYEE_COUNT}
      HrManager__JuniorsUrl: ${JUNIORS_URL}
      HrManager__TeamLeadsUrl: ${TEAM_LEADS_URL}
    depends_on:
      - hr-director

  junior-1:
    build:
      dockerfile: developer.Dockerfile
    environment:
      Developer__JuniorsUrl: ${JUNIORS_URL}
      Developer__TeamLeadsUrl: ${TEAM_LEADS_URL}
      Developer__Id: 1
      Developer__Type: Junior
    container_name: junior-1
    depends_on:
      - hr-manager

  junior-2:
    container_name: junior-2
    extends:
      service: junior-1
    environment:
      Developer__Id: 2
      Developer__Type: Junior

  junior-3:
    container_name: junior-3
    extends:
      service: junior-1
    environment:
      Developer__Id: 3
      Developer__Type: Junior

  junior-4:
    container_name: junior-4
    extends:
      service: junior-1
    environment:
      Developer__Id: 4
      Developer__Type: Junior

  junior-5:
    container_name: junior-5
    extends:
      service: junior-1
    environment:
      Developer__Id: 5
      Developer__Type: Junior

  team-lead-1:
    container_name: team-lead-1
    extends:
      service: junior-1
    environment:
      Developer__Id: 1
      Developer__Type: TeamLead

  team-lead-2:
    container_name: team-lead-2
    extends:
      service: junior-1
    environment:
      Developer__Id: 2
      Developer__Type: TeamLead

  team-lead-3:
    container_name: team-lead-3
    extends:
      service: junior-1
    environment:
      Developer__Id: 3
      Developer__Type: TeamLead

  team-lead-4:
    container_name: team-lead-4
    extends:
      service: junior-1
    environment:
      Developer__Id: 4
      Developer__Type: TeamLead

  team-lead-5:
    container_name: team-lead-5
    extends:
      service: junior-1
    environment:
      Developer__Id: 5
      Developer__Type: TeamLead
