services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: password
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
